# Arrays & Arithmetic Operations On Data using Numpy in Python - Tutorial 12 in Jupyter Notebook

## Using Numpy to perform arithmetic operations on data

In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=2)

## Creating arrays

### Creating arrays using a list

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
b = np.array([
    [10,20,30], 
    [40,50,60]
])
b

array([[10, 20, 30],
       [40, 50, 60]])

### Creating arrays via assignment

In [8]:
np.random.seed(25)
c = 36 * np.random.random(6)
c

array([31.32, 20.96, 10.04,  6.69, 14.8 ,  4.23])

In [9]:
d = np.arange(1, 35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## Performing arithmetic on arrays

In [10]:
a * 10

array([10, 20, 30, 40, 50, 60])

In [11]:
c + a

array([32.32, 22.96, 13.04, 10.69, 19.8 , 10.23])

In [12]:
c - a

array([30.32, 18.96,  7.04,  2.69,  9.8 , -1.77])

In [14]:
c * a

array([31.32, 41.92, 30.11, 26.77, 74.  , 25.35])

In [15]:
c / a

array([31.32, 10.48,  3.35,  1.67,  2.96,  0.7 ])

## Multiplying matrices and basic linrar algebra

In [19]:
A = np.array([
    [2.,4.,6.],
    [1.,3.,5.],
    [10.,20.,30.],
])
A

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [20]:
B =np.array([
    [0.,1.,2.],
    [3.,4.,5.],
    [6.,7.,8.],
])
B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [21]:
A * B

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [22]:
A @ B # matrix multiplication short for A.dot(B)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [23]:
A.dot(B)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])