# NumPy Data Science, Learn Python Shallow Copy Vs Deep Copy, Data Science With Python Programming

## Views and Copies

In [52]:
import numpy as np

In [53]:
mi_casa = np.array([-45, 31, -12, 0, 2, 25, 51,99])

In [54]:
su_casa = mi_casa

### Same are Different

In [55]:
# reference equality
mi_casa is su_casa

True

In [56]:
id(mi_casa)

140008807491104

In [57]:
id(su_casa)

140008807491104

In [58]:
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [59]:
mi_casa

array([-45,  31, -12,   0,   2,  25,  51,  99])

In [60]:
su_casa[4] = 1010

In [61]:
su_casa

array([ -45,   31,  -12,    0, 1010,   25,   51,   99])

In [62]:
mi_casa

array([ -45,   31,  -12,    0, 1010,   25,   51,   99])

In [63]:
tree_house = np.array([-45, 31, -12, 0, 2, 25, 51,99])

In [64]:
tree_house == su_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [65]:
id(tree_house)

140008807491504

In [66]:
tree_house[0] = 214

In [67]:
tree_house

array([214,  31, -12,   0,   2,  25,  51,  99])

In [68]:
mi_casa

array([ -45,   31,  -12,    0, 1010,   25,   51,   99])

In [69]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [70]:
tree_house is mi_case

False

### View: a shollow copy

In [71]:
farm_house = tree_house.view()
farm_house.shape = (2, 4)

In [72]:
tree_house

array([214,  31, -12,   0,   2,  25,  51,  99])

In [73]:
farm_house

array([[214,  31, -12,   0],
       [  2,  25,  51,  99]])

In [74]:
tree_house[3] = -111

In [75]:
tree_house

array([ 214,   31,  -12, -111,    2,   25,   51,   99])

In [76]:
farm_house

array([[ 214,   31,  -12, -111],
       [   2,   25,   51,   99]])

### Deep Copy

In [77]:
dog_house = np.copy(tree_house)

In [78]:
dog_house is tree_house

False

In [79]:
dog_house == tree_house

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [80]:
id(dog_house), id(tree_house)

(140008807451344, 140008807491504)

In [81]:
dog_house[0] = 121

In [82]:
dog_house

array([ 121,   31,  -12, -111,    2,   25,   51,   99])

In [92]:
tree_house

array([ 214,   31,  -12, -111,    2,   25,   51,   99])

## Attributes of Numpy Array

In [104]:
a = np.arange(24).reshape((2,3,4))

In [106]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [107]:
a.ndim

3

In [108]:
a.shape

(2, 3, 4)

In [109]:
a.size

24

In [110]:
a.dtype

dtype('int64')

In [111]:
a.itemsize

8

In [112]:
type(a)

numpy.ndarray

# How are standard python lists placed in memory

In [101]:
# ! pipenv install tutormagic
%load_ext tutormagic

The tutormagic extension is already loaded. To reload it, use:
  %reload_ext tutormagic


**pythontuter doesn't work with numpy**

In [94]:
%%tutor -l python3

l0 = [[1,2,3], [4,5,6], [7,8,9]]
l1 = l0

l1[1] = [11,12,13]

In [95]:
%%tutor -l python3

l0 = [[1,2,3], [4,5,6], [7,8,9]]
l1 = l0

l1[1][1] = 111213

In [96]:
%%tutor -l python3

l0 = [[1,2,3], [4,5,6], [7,8,9]]
l1 = l0[:] # shallow copy

l1[1] = [11,12,13]

In [97]:
%%tutor -l python3

l0 = [[1,2,3], [4,5,6], [7,8,9]]
l1 = l0[:] # shallow copy

l1[1][1] = 111213

In [99]:
%%tutor -l python3
from copy import deepcopy
l0 = [[1,2,3], [4,5,6], [7,8,9]]
l1 = deepcopy(l0) # deep copy

l1[1] = [11,12,13]

In [100]:
%%tutor -l python3
from copy import deepcopy
l0 = [[1,2,3], [4,5,6], [7,8,9]]
l1 = deepcopy(l0) # deep copy

l1[1] = 111213